### ISSUE TITLE
Could not train the model

### ISSUE THREAD

**Issue by shrybht** [ashitani/darknet_mnist#1]
I have the file /t10k-images -idx3-ubyte unpacked and in the right location. I have even checked the absolute path but it shows the following error:

`FileNotFoundError: [WinError 2] The system cannot find the file specified: 't10k -images-idx3-ubyte' -> '/home/shry/darknet_mnist/data/t10k-images -idx3-ubyte'`

and for the command:

`sh ./train.sh`

the error is: 

`./train.sh: line 2: ./darknet: No such file or directory`

Please help me with this.

**Comment by ashitani** [comment]
Please check the folder name. No space should be included.
- Bad: "t10k-images -idx3-ubyte"
- Good: "t10k-images-idx3-ubyte" 

And about the error on the train.sh, you should install [darknet](https://github.com/pjreddie/darknet) itself, build it, and make the symbolic-link of the darknet to this folder, as I wrote in the README.

**Comment by ashitani** [comment]
Closing this issue. If you have another suggestion, please open issue again.
