### ISSUE TITLE
Why channels=3 in cfg file?

### ISSUE THREAD

**Issue by andylai0212** [ashitani/darknet_mnist#3]
Hi, I found that channels = 3 in cfg file. 
Since the mnist dataset is in grey scale, I modified the channels = 1 in cfg file and started training and it can not converge.
Is that possible to train with channel=1 so I can have less parameter?
Thanks in advance!

**Comment by ashitani** [comment]
The image loader in darknet is fixed to load as color images, even when channel==1. You should modify darknet code to use gray scale inputs.

**Comment by linchpin-k** [comment]
Hi Ashitani.
Your post is greatly helpful!
Can I get a trained weight data (mnist_lenet.weight)?
I have no GPU so that I need a lot of days to get a mnist_lenet.weight data by training...

**Comment by ashitani** [comment]
Closing this issue. If you have another suggestion, please open an issue again.
