### ISSUE TITLE
Couldn't open file: /tmp/backup//mnist__lenet.weights

### ISSUE THREAD

**Issue by linchpin-k** [ashitani/darknet_mnist#5]
Hi Ashitani!
Thank you for your brilliant post. It is very helpful for me!
I have a question.

When I execute training following your post, I got a message like:
Couldn't open file: /tmp/backup//mnist_lenet.weights

I thought the problem is the path so that I changed from "backup = /tmp/backup/" to "backup = /tmp/backup" in mnist.dataset.
But I got same message...

How can I solve this problem?

Or, can I have pre-trained weight file for mnist dataset of darknet?

I will wait your comment.
Thank you^^

**Comment by ZLKong** [comment]
Hi 
I have the same question, did you solve the problem?

Best,
ZLKong

**Comment by ashitani** [comment]
```
mkdir /tmp/backup 
```
Before you execute train.sh.
Or, if you want to change to another folder,  modify cfg/mnist.dataset.

**Comment by ZLKong** [comment]
Thank you very much!
