### ISSUE TITLE
The loss goes to infinity.

### ISSUE THREAD

**Issue by ksr203** [ashitani/darknet_mnist#6]
![chart](https://user-images.githubusercontent.com/40992954/70632028-76e7b400-1c71-11ea-82af-41015d41aad7.png)
I'm trying to train by your code but the avg loss goes to inf.

Do you know anything about this problem?

**Comment by ksr203** [comment]
I also added batch_noramlize=1 and changed activation to leaky but it didn't work

**Comment by ashitani** [comment]
Is your data correctly downloaded and converted to RGB images?

You can check in this way.
```
$ python
>>> import cv2
>>> import numpy as np
>>> img=cv2.imread("data/mnist/images/t_00000_c5.png")
>>> print(np.shape(img))
(28,28,3)
```

If the answer is not (28,28,3), something's wrong in the download/convert process.

**Comment by ksr203** [comment]
> Is your data correctly downloaded and converted to RGB images?
> 
> You can check in this way.
> 
> ```
> $ python
> >>> import cv2
> >>> import numpy as np
> >>> img=cv2.imread("data/mnist/images/t_00000_c5.png")
> >>> print(np.shape(img))
> (28,28,3)
> ```
> 
> If the answer is not (28,28,3), something's wrong in the download/convert process.
