### ISSUE TITLE
Is your data correctly downloaded and converted to RGB images?

### ISSUE THREAD

**Issue by ksr203** [ashitani/darknet_mnist#7]
Is your data correctly downloaded and converted to RGB images?

You can check in this way.
```
$ python
>>> import cv2
>>> import numpy as np
>>> img=cv2.imread("data/mnist/images/t_00000_c5.png")
>>> print(np.shape(img))
(28,28,3)
```

If the answer is not (28,28,3), something's wrong in the download/convert process.

_Originally posted by @ashitani in https://github.com/ashitani/darknet_mnist/issues/6#issuecomment-565667895_

**Comment by ksr203** [comment]
![c](https://user-images.githubusercontent.com/40992954/70843792-8b979800-1e7b-11ea-89b7-9820121792d4.PNG)

Thank you for your help!

But the image is 3 channel ...

Do you know what happen in this issue?

**Comment by ashitani** [comment]
Does not reproduce in my environment.

Can you compare the headers of log from darknet?
Here is my log.
```
$ ./train.sh
mnist_lenet
1
layer     filters    size              input                output
    0 conv     32  5 x 5 / 1    28 x  28 x   3   ->    28 x  28 x  32  0.004 BFLOPs
    1 max          2 x 2 / 2    28 x  28 x  32   ->    14 x  14 x  32
    2 conv     64  5 x 5 / 1    14 x  14 x  32   ->    14 x  14 x  64  0.020 BFLOPs
    3 max          2 x 2 / 2    14 x  14 x  64   ->     7 x   7 x  64
    4 connected                            3136  ->  1024
    5 dropout       p = 0.50               1024  ->  1024
    6 connected                            1024  ->    10
    7 softmax                                          10
    8 cost                                             10
Learning Rate: 0.01, Momentum: 0.9, Decay: 5e-05
60000
28 28
Loaded: 0.945916 seconds
1, 0.002: 1.627004, 1.627004 avg, 0.009920 rate, 1.381257 seconds, 100 images
Loaded: 0.000108 seconds
2, 0.003: 1.613388, 1.625643 avg, 0.009841 rate, 1.404711 seconds, 200 images
Loaded: 0.000095 seconds
...
```

**Comment by ksr203** [comment]
I typed a command instead of running train.sh

the darknet execution file is in darknet_mnist/darknet

![c](https://user-images.githubusercontent.com/40992954/70869087-8432d480-1fca-11ea-83f2-bb9e9c26e246.PNG)

![c2](https://user-images.githubusercontent.com/40992954/70869051-2c946900-1fca-11ea-84e9-174881251c14.PNG)

**Comment by ashitani** [comment]
Please try the original cfg file. You have modified at least the batch size from 100 to 128.

Number of train images 60000 cannot be divided by batch size 128, and is smaller than 128x500(max_batch_size).

Some deep learning framework can not handle such an indivisible case. 
I don't remember whether darknet does. So it may not be the cause. But anyway, try the original cfg file, to isolate the problems.

**Comment by ksr203** [comment]
I tried it but it has low accuracy and it goes infinity when it has more max_batch

I think the dataset has a problem.

Can you tell me where you download the file?

I downloaded the dataset from yann's website.

http://yann.lecun.com/exdb/mnist/

**Comment by ashitani** [comment]
>I tried it but it has low accuracy and it goes infinity when it has more max_batch

Maybe, batch * max_batch cannot exceed the sample size(60000).
And anyway, increasing max_batch doesn't help to get so higher accuracy.
This is only sample and the network architecture is too shallow to get high accuracy.

>Can you tell me where you download the file?

My script downloads from the same site. Please read the script.

**Comment by ksr203** [comment]
Thank you for your kindness! 

Your answers are very helpful
